#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Tokudane.Resource", IsApplication=true)]

namespace Tokudane
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050014
			public const int MyButton = 2131034132;
			
			// aapt resource value: 0x7f050004
			public const int e_price_1 = 2131034116;
			
			// aapt resource value: 0x7f05000b
			public const int e_price_2 = 2131034123;
			
			// aapt resource value: 0x7f050010
			public const int e_price_3 = 2131034128;
			
			// aapt resource value: 0x7f050006
			public const int e_quantity_1 = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public const int e_quantity_2 = 2131034124;
			
			// aapt resource value: 0x7f050011
			public const int e_quantity_3 = 2131034129;
			
			// aapt resource value: 0x7f050008
			public const int e_unitprice_1 = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int e_unitprice_2 = 2131034125;
			
			// aapt resource value: 0x7f050012
			public const int e_unitprice_3 = 2131034130;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout2 = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int linearLayout3 = 2131034122;
			
			// aapt resource value: 0x7f05000f
			public const int linearLayout4 = 2131034127;
			
			// aapt resource value: 0x7f050009
			public const int t_lowplece_1 = 2131034121;
			
			// aapt resource value: 0x7f05000e
			public const int t_lowplece_2 = 2131034126;
			
			// aapt resource value: 0x7f050013
			public const int t_lowplece_3 = 2131034131;
			
			// aapt resource value: 0x7f050005
			public const int textView1 = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int textView2 = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int textView3 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int textView4 = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
